[colors]
[colors.primary]
background = "0x1e2d24"
foreground = "0xe5e5d5"

[colors.normal]
black = "0x5c5c5c"
red = "0xcc6666"
green = "0xb8bb26"
yellow = "0xfabd2f"
blue = "0x83a598"
magenta = "0xd3869b"
cyan = "0x8ec07c"
white = "0xe5e5d5"

[colors.bright]
black = "0x928374"
red = "0xfb4934"
green = "0xb8bb26"
yellow = "0xfabd2f"
blue = "0x83a598"
magenta = "0xd3869b"
cyan = "0x8ec07c"
white = "0xfbf1c7"
